blueprints:
  main_bp:
    root_path: main_bp
    routes:
      test-route: /test
      code-fixer-route: /code-fixer
      chatbot-route: /chatbot
      prompt-injection-route: /prompt-injection
      crag-route: /crag
